export const RU_NAMES = {
    manicure_without: 'Маникюр (без покрытия)',
    manicure_coating: "Маникюр с покрытием 'гель-лак'",
    manicure_removal_coating: "Маникюр со снятием и покрытием 'гель-лак'",
    manicure_french: 'Маникюр французский или лунный',
    gradient: 'Градиент (аэрография)',
    rubbing: 'Втирка',
    manicure_extension_coating: 'Маникюр + наращивание + покрытие в один тон',
    manicure_extension_french: "Маникюр + наращивание + покрытие 'френч'",
    manicure_correction_coating: 'Маникюр + коррекция + покрытие в один тон',
    manicure_correction_french: "Маникюр + коррекция + покрытие 'френч'",
    removing_extension: 'Снятие наращенных ногтей',
    removing_gel: 'Снятие гель-лака',
    repair: 'Ремонт ногтя',
    nail_extension: 'Наращивание ногтя',
    pedicure_without: 'Педикюр (без покрытия)',
    pedicure_coating: 'Педикюр + однотонное покрытие',
    pedicure_removal_coating: 'Педикюр со снятием и однотонным покрытием',
};
